name: Manually Publish to Conda-Forge

on:
  workflow_dispatch
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: conda-forge/conda-publish-action@v1.3
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.CONDA_INITIALIZE }}
        platforms: 'win osx linux'
