name: Publish to Conda-Forge

on:
  release:
    types:
      - created
      - edited

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Create Conda Env. from environment file
        uses: conda env create --file=conda/environments.yml

      - name: Activate conda environment
        run: conda activate sprit-env

      - name: Install Conda-Forge Client
        run: conda install -c conda-forge conda-forge-ci-setup -y

      - name: Build and Upload Package
        env:
          CONDA_FORGE_TOKEN: ${{ secrets.CONDA_INITIALIZE }}
        run: conda smithy ci  # using smithy
