name: Generate Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install numpydoc
      - name: Generate documentation
        run: python -m pydoc -w sprit
      - name: Push to wiki repository
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git clone https://github.com/RJbalikian/SPRIT.wiki.git
          mv docs/hvsrtools.html SPRIT.wiki/
          cd SPRIT.wiki/
          # git config user.name "RJbalikian"
          # git config user.email "rileybalikian@outlook.com"
          git add .
          git commit -m "Update wiki documentation"
          git push origin master
