# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published, edited]
    tags:
      - 'v*-alpha'
      - 'v*-beta'
      - 'v*-rc'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Distribution
        run: python -m build --sdist --wheel --outdir dist/
           
  publish_test:
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Publish distribution 📦 to Test PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository-url: https://test.pypi.org/legacy/
            package-dir: ./dist/

  publish_pypi:
      needs: build
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags')

      steps:
        - name: Publish distribution 📦 to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
            repository-url: https://upload.pypi.org/legacy/
            package-dir: ./dist/
